language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm test
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: HcuA+iwfDmy7Jpj7NOeUEn3469UppZ6TaY6vWSniVtbmJVLHccanb80AgalGlirnHuYCF5S+fTiZukVjGjzH84XWhbuxuPdRP50Nz7fkXRYixUwoxWbMBh/8Pu0SPXS2hs6VpVZxjLpNC3ibYaBQOelW5v3FDqQEqoybFsq9eHID2CbLk2VkOjEQ+9VAZEOIZGvKRkM/qjcgZza0eN0aYHSwvfp9ytPq4NqzrrRHrvIw1moHLdKWbiQ+rkzSYsa7sCZlf75DQHS3697Lpx+GrcGvMWOmg6iF1r/cr2G7WLy8zmKPOtQe2+KtDXSp/wexSHsmC2n3vN90vJ595N5HGPYWl4GkFKc8cSCztSSslav473ZuhPKpevzAsEE4bg1yZm4MvLJbKMfudDWtLqDdaNsMBs0KEJ4kOqwkbO+rJoCjmX+JH1uOnjTsnRd3Amh+0liK8dMIE+ZSXUOOlXPF6CFwH6DHtveF4gzhpz/nIBw75lAqROYV/Fa/H4WV7bL95kY9BmQCbhl4DIzcEsa51r5IUflJvA/gzbCzlrxfzf8/EqcxS8SUI26EtI5ZhPJ4k8/mYQcC2hH2dxqUq2ruCWy/kih/NKhPTYjaBmPJpBJs7wVC/XSRDSF4vg8nTRUguT/9BInbwBusIIJfeuh96+ipvG+On4R8ewSIyQqZUDM=
  on:
    tags: true
    repo: mathjax/MathJax-a11y
